### PR TITLE
Requests' sessions used as a client.

### LINKED ISSUE #34: Client doesn't use connection pooling.
If `requests.Session`s are used instead of the module level methods, then the client will automatically take advantage of connection pooling.

Relatedly, `requests_futures` also provides a `FutureSession` which would make the threaded client unnecessary.

### PR DESCRIPTION
**Pull request by coady**
Fixes #34.

### CODE REVIEW

**Comment by bryanhelmig** [comment]
I'm not positive adding https://github.com/ross/requests-futures as a dependency is destined for mainline - I'll let @avelis chime in with his thoughts though.

**Comment by bryanhelmig** [comment]
That said - thank you for the contribution!

**Comment by coady** [comment]
Sure, switching the client to uses sessions is still worthwhile even without the futures dependency.

**Comment by avelis** [comment]
@coady As long as threading is still preserved I will merge the PR. Other developers have explicitly noted that a benefit of this library.

If requests-futures does turn into staleware (at any point in the future), then refactoring the client to use requests.sessions will have to occur later.

**Comment by coady** [comment]
Reverted to merely use sessions;  `Client` otherwise left alone.

Another option going forward is to use `concurrent.futures` directly.  It's a backport of the standard library, and `requests-futures` is just a small wrapper around it.

**Comment by bryanhelmig** [comment]
🎊

**Comment by avelis** [comment]
@coady `concurrent.futures` could be considered in a future PR. Thank you for your time and attention to diligently contribute this PR to meet your needs and further enhance this library.

**Pull request merged**
