### PR TITLE
implemented django 1.7 support and tox testing

### PR DESCRIPTION
**Pull request by sherzberg**

### CODE REVIEW

**Comment by calind** [comment]
Hi @bryanhelmig, are there any plans to upstream these changes? Will future django releases be supported?

**Comment by avelis** [comment]
:+1: To merge this in and get a release with Django 1.7 support.

**Comment by avelis** [comment]
annnndddd bump :+1:

**Comment by calind** [comment]
Meanwhile I have forked it and added few extras at https://github.com/PressLabs/django-rest-hooks-ng

**Pull request closed without merging**
