### PR TITLE
[DRH-1]: Add Power Support ppc64le

### PR DESCRIPTION
**Pull request by nagesh4193**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing.

### CODE REVIEW

**Comment by avelis** [comment]
@nagesh4193 I am not sure why this needs a zapier/jira . However, if the travis passes tests I can look at merging.

**Comment by nagesh4193** [comment]
@avelis Even I think it wouldn't require a jira ticket. The TravisCI tests passed, can you please help in merging? Thank you.

**Review by avelis — APPROVED** [review]

**Comment by avelis** [comment]
@nagesh4193 It would appear that the JIRA ticket is required. This isn't my organization as I am a maintainer for the repo. Any outreach to Zapier hasn't been all that helpful.

**Comment by avelis** [comment]
@gaurdro Any insight into the required Jira status? Could you possibly change the settings to disable that requirement for this repo?

**Comment by deepeeess** [comment]
I know this was last commented on back in December but I am wondering if somebody knows whether or not this package is still officially maintained.  We are considering implementing it and this will weigh in on our technology decision.

**Comment by avelis** [comment]
@deepeeess I have been doing my best to maintain it. Being under Zapier's repo has created new challenges. I might suggest thorn for now. https://thorn.readthedocs.io/en/stable/getting-started/django.html

**Comment by deepeeess** [comment]
Thank you for the recommendation @avelis.

**Comment by avelis** [comment]
@deepeeess The thorn library also appears a little out of date as well. ugh.

**Comment by avelis** [comment]
@deepeeess My best advice is to re-open this PR to see if the JIRA ticket associated is removed.

**Comment by avelis** [comment]
@nagesh4193 Can you re-open this PR to see if the JIRA ticket association is removed.

**Pull request merged**
