### PR TITLE
Use json instead of django simplejson (depreciated)

### PR DESCRIPTION
**Pull request by sebastibe**
Hi there, thank you for this great lib.

I just wanted to suggest to switch from the `django.utils.simplejson` to the `json` module as the first one will be depreciated from Django 1.7 (and raises annoying warnings in 1.6) and is not really useful anymore since Python 2.7.

### CODE REVIEW

**Comment by lylepratt** [comment]
Please merge this!

**Comment by bryanhelmig** [comment]
Simple change - sorry we missed it!

**Comment by lylepratt** [comment]
Cool thanks. How long till its normally available via pip?

**Comment by bryanhelmig** [comment]
I'll try and get something out this weekend. :-D

**Pull request merged**
